server:
  port: 12001
spring:
  profiles:
    active: test
  application:
    name: SERVICE-TEACHER
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 1
    password: 15031911155Lh@=
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 3000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

eureka:
  instance:
    instance-id: teacher-${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
---
spring:
  profiles: dev
  redis:
    host: linaxhua.cn
    port: 6600
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
---
spring:
  profiles: test
  redis:
    host: redis-8cde58f-dcs-emww.dcs.huaweicloud.com
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.49:6001/eureka