server:
  port: 8001
spring:
  profiles:
    active: test
  application:
    name: SERVICE-PROVIDER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  instance:
    instance-id: provider-${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
ribbon:
  eureka:
    enabled: true
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/classsign?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: mysql
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://rm-uf6ck33a76x59qa8q9o.mysql.rds.aliyuncs.com:3306/classsign?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: classsign
    password: classsign
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.49:6001/eureka